server:
  port: 9011

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://39.101.143.227:3306/gdmt
    username: root
    password: Gdmt123456


# mybatis配置
mybatis:
  configuration:
    map-underscore-to-camel-case: on

#公钥的文件路径
rsa:
  key:
#    #windows开发测试
#    pubKeyFile: D:/key/public_key
    pubKeyFile: /usr/key/public_key