spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://39.101.143.227:3306/gdmt
    username: root
    password: Gdmt123456

mybatis:
  configuration:
    map-underscore-to-camel-case: true

#公钥的文件路径
rsa:
  key:
    pubKeyFile: /usr/key/public_key

server:
  port: 8094